---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`hija_de_hector`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`hermana_de_tito`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`hija_de_elena`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`hermana_de_ana`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`mama_de_gustavo`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`tia_de_gonzalo`"
  checked: false
name: Identidad, revisada
