---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Pepita`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`@energia`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`una_ciudad`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`@ciudad`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Iruya`"
  checked: true
name: Lo 100to
